App\UristBundle\Entity\Certificate:
    type: entity
    repositoryClass: App\UristBundle\Repository\CertificateRepository
    table: certificate
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            nullable: FALSE
            unique: true
        slug:
            type: string
            length: 128
            gedmo:
                slug:
                    separator: _
                    style: camel
                    fields:
                        - name
        path:
            type: string
            length: 128
            nullable: FALSE
            unique: true
    lifecycleCallbacks:
        prePersist: [preUpload]
        preUpdate: [beforeUpdateAction]
        postPersist: [upload]
        postUpdate: [onUpdateAction]
        postRemove: [removeUpload]