App\UristBundle\Entity\User:
    type: entity
    repositoryClass: App\UristBundle\Repository\UserRepository
    table: user
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        username:
            type: string
            length: 25
            nullable: FALSE
            unique: true
        email:
            type: string
            length: 50
            nullable: FALSE
            unique: TRUE
        password:
            type: string
            length: 64
            nullable: FALSE
        created_at:
            type: datetime
            nullable: FALSE
        is_active:
            type: boolean
            length: 1
            nullable: TRUE
    oneToOne:
        user_profile:
            targetEntity: UserProfile
            mappedBy: user
    manyToMany:
        user_roles:
            targetEntity: Role
            joinTable:
                name: users_roles
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    role_id:
                        referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [setCreatedAtValue]
