<?php

namespace App\UristBundle\Repository;

/**
 * CertificateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CertificateRepository extends \Doctrine\ORM\EntityRepository
{
	/**
     * Получить одну сущность сертификата
     * @param $slug
     * @return object сущность сертификата
     */
    public function getCertificate($slug)
    {
        $qb = $this->createQueryBuilder('certificate')
                   ->select('certificate')                
                   ->where('certificate.slug = (:slug)')
                   ->setParameter(':slug', $slug)
        ;
        $query = $qb->getQuery();
        $result = $query->getOneOrNullResult();

        return $result;
    }
}
