<?php

namespace App\UristBundle\Repository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends \Doctrine\ORM\EntityRepository
{
	/**
     * Полуенние массива документов
     * @return array массив с документами
     */
    public function getDocumentList()
	{
        $qb = $this->createQueryBuilder('d')
                   ->select('d.name, d.path', 'd.slug')
                   ->orderBy('d.name', 'ASC')
        ;

        $query = $qb->getQuery();
        $result = $query->getArrayResult();
       
        return $result;
	}
    /**
     * [getDocumentEntityList Получить список сущностей документов]
     * @return [type] [description]
     */
    public function getDocumentEntityList()
    {
        $qb = $this->createQueryBuilder('d')
                   ->select('d', 'c')
                   ->join('d.category', 'c')
                   ->orderBy('d.name')
        ;
        $query = $qb->getQuery();
        $result = $query->getResult(); 
        return $result;
    }

    /**
     * Получить одну сущность документа
     * @param $slug
     * @return object сущность документа
     */
    public function getDocument($slug)
    {
        $qb = $this->createQueryBuilder('d')
                   ->select('d')
                   ->where('d.slug = :slug')
                   ->setParameter(':slug', $slug)
        ;
        $query = $qb->getQuery();
        $result = $query->getOneOrNullResult();
           
        return $result;
    }
}
