<?php

namespace App\UristBundle\Repository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * [findRolesByName Найти сущности ролей по именам]
	 * @param  [array] $rolesNames [массив с именами]
	 * @return [array] $result [массив с сущностями ролей]
	 */
	public function findRolesByName($rolesNames)
	{
		$qb = $this->createQueryBuilder('r')
				   ->select('r')
				   ->where('r.name IN (:names)')
				   ->setParameter(':names', $rolesNames)
		;
		$query = $qb->getQuery();
        $result = $query->getResult();

        return $result;
	}
}
