<?php

namespace App\UristBundle\Repository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * [getService получить сущность услуги]
     * @param  [string] $slug [slug идентификатор]
     * @return [object]       [сущность услуги]
     */
    public function getService($slug)
    {
        $qb = $this->createQueryBuilder('s')
                   ->select('s')
                   ->where('s.slug = :slug')
                   ->setParameter(':slug', $slug)
        ;
        $query = $qb->getQuery();
        $result = $query->getOneOrNullResult();
           
        return $result;
    }
}
