<?php

namespace App\UristBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * [findUsersNoSpecRoles Найти пользователей без определенных ролей]
     * @param  [array] $roles [сущности ролей]
     * @return [array] $result [массив сущностей пользователей]
     */
	public function findUsersNoSpecRoles($roles)
	{
        $qb = $this->createQueryBuilder('u');
        $qb->select('u.id, u.username, u.email', 'u.is_active');

        if ( $roles && is_array($roles) ){
            $counter = 1;
            foreach ($roles as $role) {
                ($counter === 1) ? $qb->where(':role_'.$counter.' NOT MEMBER OF u.user_roles') : $qb->andWhere(':role_'.$counter.' NOT MEMBER OF u.user_roles');
                $qb->setParameter(':role_'.$counter, $role);
            }
        }
        $query = $qb->getQuery();
        $result = $query->getArrayResult();

        return $result;
    }
}
